// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wychumpifglxebseikkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5Y2h1bXBpZmdseGVic2Vpa2t6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwNDcxOTAsImV4cCI6MjA1MTYyMzE5MH0.yeJ063U8Yd9lUUDQ2uSoBK3BNcqXWlAJS_-T8u5UI0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);